CREATE TABLE IF NOT EXISTS "Catalog"."OrderChecked"
(
    "Id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    "OrderCode" text COLLATE pg_catalog."default",
    "OrderId" bigint NOT NULL,
    "ProductCode" text COLLATE pg_catalog."default",
    "ProductBarCode" text COLLATE pg_catalog."default",
    "BranchId" bigint NOT NULL,
    "UserName" text COLLATE pg_catalog."default",
    "CreatedAt" timestamp with time zone NOT NULL,
    "CreatedBy" bigint NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    "UpdatedBy" bigint NOT NULL,
    "Count" double precision NOT NULL DEFAULT 0.0,
    CONSTRAINT "PK_OrderChecked" PRIMARY KEY ("Id")
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS "Catalog"."OrderChecked"
    OWNER to postgres;